version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    working_directory: /src
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          export VERSION=${CIRCLE_TAG/v/}
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t whefter/cron:$VERSION -t whefter/cron:latest .
          docker push whefter/cron:$VERSION
          docker push whefter/cron:latest
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
