name: scheduled build & push of latest version

on:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    name: build and publish Docker image
    steps:
      - name: checkout code to list tags
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: set latest tag var
        id: latestTag
        run: echo ::set-output name=tag::$(git tag -l 'v*' --sort=taggerdate | tail -n 1)
      - name: checkout latest tag
        uses: actions/checkout@v2
        with:
            ref: ${{ steps.latestTag.outputs.tag }}
      - name: build and push docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: whefter/cron
          tags: latest,${{ steps.latestTag.outputs.tag }}
          push: true
