name: scheduled build & push of latest version

on:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    name: build and publish Docker image
    steps:
      - name: checkout code to list tags
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: '386,amd64,arm64,arm'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: set latest tag var
        id: latestTag
        run: echo ::set-output name=tag::$(git tag -l 'v*' --sort=taggerdate | tail -n 1)
      - name: checkout latest tag
        uses: actions/checkout@v3
        with:
            ref: ${{ steps.latestTag.outputs.tag }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: whefter/cron:latest,whefter/cron:${{ steps.latestTag.outputs.tag }}
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v6,linux/arm/v7,linux/386
